ARC-1441 add yamlfix job and linting

diff --git a/.github/workflows/yaml_linter.yml b/.github/workflows/yaml_linter.yml
--- a/.github/workflows/yaml_linter.yml
+++ b/.github/workflows/yaml_linter.yml
@@ -1,9 +1,29 @@
-name: Yaml Lint
-on: [push]  # yamllint disable-line rule:truthy
+---
+name: Check for properly formatted docs
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+permissions:
+  contents: read
 jobs:
-  lintAllTheThings:
+  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: yaml-lint
-        uses: ibiqlik/action-yamllint@v3
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+      - name: Install dependencies
+        run: |
+          pip install yamlfix
+      - name: Check that no yaml fixes need be made
+        run: |
+          YAMLFIX_OUTPUT=$(yamlfix .)
+          if ! [[ $YAMLFIX_OUTPUT == *" 0 fixed"* ]]; then
+            echo "Run yamlfix . to fix the errors below"
+            echo $YAMLFIX_OUTPUT
+            exit 1 
+          fi
